name: Auto-run package.py
on:
    workflow_dispatch:
    schedule:
     - cron: '0 8 * * *'
jobs:
  run-package:
    runs-on: windows-latest
    steps:
    - name: Git long allow
      run : git config --global core.longpaths true
    - name: Git clone
      run: git clone https://github.com/Sam5440/Genshin_Impact_Teleport
    - name: Run package.py
      run: python Genshin_Impact_Teleport/package.py
    - name: Auto push
      run: |
        cd ./zips
        git init
        git config --local user.email "Y_sam5440@outlook.com"
        git config --local user.name "Sam5440"
        git add .
        git commit --allow-empty -m "daily sync"
        git branch -m master main
        git config --global user.token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        git remote add origin https://github.com/${{ github.repository }}
        git push -u origin main -f
